project:
  type: book

book:
  title: "panelView -- User Manual"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - 01-treat.Rmd
    - 02-outcome.Rmd
    - 03-bivariate.Rmd
    - 04-network.Rmd
    - aa-changelog.Rmd
    - references.qmd

delete_merged_file: true

bibliography: references.bib

nocite: |
  @*

format:
  html:
    theme: cosmo
    df-print: paged
    code-fold: false
    code-tools: true
    code-link: true

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
